services:
  gemini-chat:
    image: nginx:alpine
    container_name: gemini-chat
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 20M
